### ISSUE TITLE
Going "back" results in an error

### ISSUE THREAD

**Issue by Semir1212** [humhub-contrib/auto-follow#2]
Clicking "back" within the module configuration leads to an error site.

**Comment by MasterMindNET** [comment]
### Found a quick and easy fix for this problem!

Good day, @Semir1212!
I have managed to fix it.
you just need to edit the next files:
> lines 29-31 in protected\modules\auto-follow\controllers\AdminController.php

```
        // if there's no `Yii::$app->request->referrer` we can redirect to Yii::$app->homeUrl. that's it
        $prevPage = Yii::$app->request->referrer ?: Yii::$app->homeUrl; 
        // passing $prevPage variable to our view file
        return $this->render('index', ['model' => $model, 'prevPage' => $prevPage]);
```

> line 26 in protected\modules\auto-follow\views\admin\index.php

`<?= Html::a(Yii::t('base', 'Back'), $prevPage, ['class' => 'btn btn-default pull-right']); ?>`

[Full code can found here](https://hastebin.com/ikivuyazix.xml)

Please let me know how can I make a push request if you need to fix it, explain to me the basic rules of how you do it and if you have any standards of making commits
Please let me know if there's something else that can be improved!

**Comment by luke-** [comment]
@MasterMindNET Awesome, can you please create a pull request for this fix?

**Comment by Semir1212** [comment]
Great, thank you! @MasterMindNET

**Comment by MasterMindNET** [comment]
> @MasterMindNET Awesome, can you please create a pull request for this fix?

Yeah, that is ready to roll out!
