### ISSUE TITLE
Auto Member

### ISSUE THREAD

**Issue by phenze** [humhub-contrib/auto-follow#5]
Hello,

Is it possible to an a "auto-member" feature ?

Technical this should be no problem: I have solved this with replacing onAfterUserCreate function with the following.

```php
public static function onAfterUserCreate($event)
    {
        $user = $event->sender;
        $module = Yii::$app->getModule('auto-follow');

        foreach ($module->getAutoFollows() as $container) {

            if ($container instanceof Space && $container->isMember($user->id)) {
                continue;
            }

            if ($container instanceof Space && !$container->isMember($user->id)) {
                $container->addMember($user->id);
            }

            // $container->follow($user);

        }
    }
```

Would be nice to add an option in the configuration screen.
Thank you.

**Comment by luke-** [comment]
Why don't you use the Default Spaces for this? Here, too, all users automatically become members. 

![image](https://user-images.githubusercontent.com/4736168/109026648-42b6b280-76c0-11eb-9b30-d20ffbf8cba4.png)

**Comment by phenze** [comment]
Thank you. I didn't notice that option.
